spring.application.name=movie-recommendation

# ===== STARTUP OPTIMIZATION =====
spring.main.lazy-initialization=true
spring.data.jpa.repositories.bootstrap-mode=lazy
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false

# ===== DISABLE SWAGGER IN PROD =====
springdoc.api-docs.enabled=${SPRINGDOC_ENABLED:false}
springdoc.swagger-ui.enabled=${SPRINGDOC_ENABLED:false}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.jdbc.sslmode=require
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.keepaliveTime=30000
spring.datasource.hikari.maxLifetime=1800000
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.validationTimeout=5000

spring.data.elasticsearch.repositories.enabled=true
spring.elasticsearch.uris=${ES_URL}
#spring.elasticsearch.username=${ES_USERNAME}
#spring.elasticsearch.password=${ES_PASSWORD}
spring.elasticsearch.connection-timeout=10s
spring.elasticsearch.socket-timeout=30s
spring.elasticsearch.rest-client.headers.Accept=application/vnd.elasticsearch+json;compatible-with=7
spring.elasticsearch.rest-client.headers.Content-Type=application/vnd.elasticsearch+json;compatible-with=7

es.url=${ES_URL}
es.host=${ES_HOST}
es.username=${ES_USERNAME}
es.password=${ES_PASSWORD}

logging.level.org.springdoc=WARN
logging.level.org.springframework.web=WARN

logging.level.root=INFO
logging.level.nlu.fit.movie_backend=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=when-authorized
management.endpoint.health.probes.enabled=true
management.health.db.enabled=false
management.health.diskspace.enabled=false

management.metrics.export.prometheus.enabled=true
management.endpoint.prometheus.enabled=true

management.metrics.tags.application=movie-recommender-system
management.metrics.tags.environment=production

management.metrics.enable.jvm=false
management.metrics.enable.process=false
management.metrics.enable.system=false

management.metrics.distribution.percentiles-histogram.http.server.requests=false

services.chatbot=${CHATBOT_URL}
services.recommendation=${RECO_URL}
services.hfToken=${HF_TOKEN}

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS}

logging.level.org.springframework.security=WARN