spring.application.name=movie-recommendation

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2

spring.data.elasticsearch.repositories.enabled=true
spring.elasticsearch.uris=${ES_URL}
spring.elasticsearch.username=${ES_USERNAME}
spring.elasticsearch.password=${ES_PASSWORD}
spring.elasticsearch.connection-timeout=10s
spring.elasticsearch.socket-timeout=60s
spring.elasticsearch.rest-client.headers.Accept=application/vnd.elasticsearch+json;compatible-with=7
spring.elasticsearch.rest-client.headers.Content-Type=application/vnd.elasticsearch+json;compatible-with=7

services.chatbot=${CHATBOT_URL}
services.recommendation=${RECO_URL}